/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 food.gltf 
Author: nikitakorneev89 (https://sketchfab.com/nikitakorneev89)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/fast-food-f90b29bb27ad40319535c9909404189c
Title: Fast-food
*/

import React, { useRef } from 'react';
import { useFrame } from '@react-three/fiber'; // Correctly import useFrame
import { useGLTF } from '@react-three/drei';


export function Model(props) {
  const groupRef = useRef(); // Create a reference for the group
  const { nodes, materials } = useGLTF('/food.gltf');

  // This function is called every frame, rotating the model
  useFrame(() => {
    if (groupRef.current) {
      // Adjust the rotation speed here by changing the value (e.g., 0.01)
      groupRef.current.rotation.y += 0.01;
    }
  });

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.017}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.cheez_mayonez_0.geometry} material={materials.mayonez} position={[84.014, 34.496, 20.528]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.luk014_salat_0.geometry} material={materials.salat} position={[66.674, 31.252, 7.574]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.luk017_salat_0.geometry} material={materials.salat} position={[55.901, 40.973, 14.683]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.luk12_salat_0.geometry} material={materials.salat} position={[66.791, 36.646, -14.851]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.luk25_salat_0.geometry} material={materials.salat} position={[64.277, 35.795, -16.792]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.lyk015_salat_0.geometry} material={materials.salat} position={[66.54, 21.281, 22.872]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.mayonez_ketchup_0.geometry} material={materials.ketchup} position={[43.124, 43.832, -4.308]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.meat011_salat_0.geometry} material={materials.salat} position={[49.03, 44.062, 15.24]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.meat016_salat_0.geometry} material={materials.salat} position={[69.437, 29.888, 26.478]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.meat029_salat_0.geometry} material={materials.salat} position={[59.935, 21.239, -25.396]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.meat10_salat_0.geometry} material={materials.salat} position={[54.939, 36.091, -27.542]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.meat20_salat_0.geometry} material={materials.salat} position={[78.105, 22.917, 13.885]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.meat24_salat_0.geometry} material={materials.salat} position={[-69.872, 10.18, 62.616]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.meat27_salat_0.geometry} material={materials.salat} position={[65.068, 20.335, -20.059]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.meat28_salat_0.geometry} material={materials.salat} position={[42.215, 41.44, -6.235]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.meat9_salat_0.geometry} material={materials.salat} position={[66.971, 41.031, 24.981]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.ogurec013_salat_0.geometry} material={materials.salat} position={[60.972, 40.081, -11.288]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.ogurec08_salat_0.geometry} material={materials.salat} position={[67.902, 19.446, -6.805]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.ogurec18_salat_0.geometry} material={materials.salat} position={[67.614, 28.712, 25.936]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.ogurec26_salat_0.geometry} material={materials.salat} position={[60.972, 40.081, -11.288]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.ogurec33_salat_0.geometry} material={materials.salat} position={[7.529, 12.087, -61.752]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.ogurec_1_salat_0.geometry} material={materials.salat} position={[56.044, 37.214, -5.214]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.origana_salat_0.geometry} material={materials.salat} position={[86.399, 20.232, 18.496]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.origana001_salat_0.geometry} material={materials.salat} position={[70.376, 33.191, -5.53]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.petrushka030_salat_0.geometry} material={materials.salat} position={[57.219, 47.897, -7.494]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.petrushka21_salat_0.geometry} material={materials.salat} position={[78.927, 19.498, -6.736]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.petrushka23_salat_0.geometry} material={materials.salat} position={[-25.361, 7.545, 65.733]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.potato_salat_0.geometry} material={materials.salat} position={[84.059, 43.039, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.potato031_salat_0.geometry} material={materials.salat} position={[72.157, 40.784, -8.692]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.salat032_salat_0.geometry} material={materials.salat} position={[-17.2, 15.956, -56.698]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.salat19_salat_0.geometry} material={materials.salat} position={[35.566, 24.299, -2.795]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.salat_1_salat_0.geometry} material={materials.salat} position={[58.508, 21.43, 8.976]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.tarelka_blude_0.geometry} material={materials.blude} position={[-27.366, 9.725, 9.618]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.tomato_salat_0.geometry} material={materials.salat} position={[19.605, 9.014, 63.108]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.tomato_2_salat_0.geometry} material={materials.salat} position={[75.73, 20.818, 19.662]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.tomato_3_salat_0.geometry} material={materials.salat} position={[66.927, 32.604, -22.432]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Table_Table_0.geometry} material={materials.Table} position={[-36.668, -7.096, -20.604]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.shava002_Shava_0.geometry} material={materials.Shava} position={[6.388, 33.673, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.botl_base_botl_opacity_0.geometry} material={materials.botl_opacity} position={[-66.283, 48.61, -122.032]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.botl_inside_botl_inside_0.geometry} material={materials.botl_inside} position={[-66.283, 48.61, -122.032]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.botle_cap_botl_cap_0.geometry} material={materials.botl_cap} position={[-66.283, 48.61, -122.032]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/food.gltf')
